registry:
  image: "registry:2.0"
  command: >
  net: "host"
  restart: "always"
  volumes:
    - "/vagrant_data:/vagrant_data"
  environment:
    REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /vagrant_data/registry
    REGISTRY_HTTP_ADDR: 0.0.0.0:5000
  ports:
    - "5000:5000"
dnsmasq:
  image: "172.16.16.15:5000/dnsmasq-local"
  net: "host"
  restart: "always"
  volumes:
    - "/vagrant_data/dnsmasq/dnsmasq.conf.d:/etc/dnsmasq.conf.d"
    - "/vagrant_data/dnsmasq/tftpboot:/var/tftpboot"
nginx:
  image: "172.16.16.15:5000/nginx-local"
  net: "host"
  restart: "always"
  volumes:
    - "/vagrant_data/nginx:/etc/nginx"
    - "/vagrant_data/static:/data"
etcd:
  image: "172.16.16.15:5000/etcd-local:v2.0.10"
  command: >
    --advertise-client-urls http://172.16.16.15:2379 
    --data-dir /var/lib/etcd2
    --listen-client-urls http://172.16.16.15:2379,http://127.0.0.1:2379 
    --listen-peer-urls http://172.16.16.15:2380
    --max-wals 0
    --name etcd01
    --initial-cluster-state new
    --initial-cluster-token etcd-cluster
    --initial-cluster etcd01=http://172.16.16.15:2380
    --advertise-client-urls http://172.16.16.15:2379
  net: "host"
  ports:
    - "2379:2379"
    - "2380:2380"
  restart: "always"
  volumes:
    - "/vagrant_data/etcd:var/lib/etcd2"
    - "/vagrant_data/etcd/ssl/certs/:/etc/ssl/certs"
fleetd:
  image: "172.16.16.15:5000/fleetd:0.10.2"
  command: >
    -etcd-servers http://172.16.16.15:2379
  net: "host"
  restart: "always"
apiserver:
  image: "172.16.16.15:5000/kube-apiserver:0.18.2"
  command: >
    --etcd-servers=http://172.16.16.15:2379
    --insecure-bind-address=0.0.0.0
    --insecure-port=8080
    --logtostderr=true
    --service-cluster-ip-range=10.1.1.0/24
    --v=0
  net: "host"
  restart: "always"
  volumes:
    - "/vagrant_data/kubernetes:/etc/kubernetes"
    - "/vagrant_data/share/ca-certificates:/etc/ssl/certs"
    - "/vagrant_data/run/kubernetes:/var/run/kubernetes"
controllermanager:
  image: "172.16.16.15:5000/kube-controller-manager:0.18.2"
  command: >
    --logtostderr=true
    --master=http://172.16.16.15:8080
    --cloud-provider=""
    --v=0
  net: "host"
  restart: "always"
  volumes:
    - "/vagrant_data/kubernetes:/etc/kubernetes"
    - "/vagrant_data/share/ca-certificates:/etc/ssl/certs"
scheduler:
  image: "172.16.16.15:5000/kube-scheduler:0.18.2"
  command: >
    --master=http://172.16.16.15:8080
    --logtostderr=true
    --v=0
  net: "host"
  restart: "always"
  volumes:
    - "/vagrant_data/kubernetes:/etc/kubernetes"
    - "/vagrant_data/share/ca-certificates:/etc/ssl/certs"
register:
  image: "172.16.16.15:5000/kube-register:0.0.4"
  command: >
    --api-endpoint="http://172.16.16.15:8080"
    --fleet-endpoint="http://172.16.16.15:2379"
    --healthz-port="10255"
    --metadata="kube-role=node"
    --sync-interval=10
  net: "host"
  restart: "always"
