# based on https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/addons/dns/skydns-rc.yaml.in
apiVersion: v1beta3
kind: ReplicationController
metadata:
  name: kube-dns-v3
  namespace: default
  labels:
    k8s-app: kube-dns-v3
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: kube-dns
    version: v3
  template:
    metadata:
      labels:
        k8s-app: kube-dns
        version: v3
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
        - name: etcd
          image: 172.16.16.15:5000/etcd
          args:
            # command = "/etcd"
            - -listen-client-urls
            - http://127.0.0.1:2379,http://127.0.0.1:4001
            - -advertise-client-urls
            - http://127.0.0.1:2379,http://127.0.0.1:4001
            - -initial-cluster-token
            - skydns-etcd
        - name: kube2sky
          image: 172.16.16.15:5000/kube2sky
          args:
            # command = "/kube2sky"
            -  -domain=kubernetes.local
            -  -kube_master_url=http://172.16.16.15:8080
            # - -kubecfg_file=/etc/dns_token/kubeconfig
          # volumeMounts:
          #  - mountPath: /etc/dns_token
          #    name: dns-token
          #    readOnly: true
        - name: skydns
          image: 172.16.16.15:5000/skydns:2015-03-11-001
          args:
            # command = "/skydns"
            - -machines=http://localhost:4001
            - -addr=0.0.0.0:53
            - -domain=kubernetes.local.
          ports:
            - containerPort: 53
              name: dns
              protocol: UDP
            - containerPort: 53
              name: dns-tcp
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - nslookup kubernetes.default.kubernetes.local localhost >/dev/null
            initialDelaySeconds: 30
            timeoutSeconds: 5
      dnsPolicy: Default  # Don't use cluster DNS.
      # volumes:
      #  - name: dns-token
      #    secret:
      #        seretName: token-system-dns
