apiVersion: v1beta3
kind: ReplicationController
metadata:
  name: heapster-v1
  namespace: default
  labels:
    k8s-app: heapster
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: heapster
    version: v1
  template:
    metadata:
      labels:
        k8s-app: heapster
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
        - image: 172.16.16.15:5000/heapster
          name: heapster
          command:
            - /heapster
            - --source=kubernetes:http://kubernetes-ro?auth=
            - --sink=influxdb:http://influxdb:8086
          volumeMounts:
            - name: ssl-certs
              mountPath: /etc/ssl/certs
              readOnly: true
            # - name: monitoring-token
            #  mountPath: /etc/kubernetes/kubeconfig
            #  readOnly: true

      volumes:
        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs
        # - name: monitoring-token
        #  secret:
        #    secretName: token-system-monitoring
